---

- hosts: clusterBrokerNodes:clusterBrokerAddNodes
  gather_facts: true
  serial: 1
  roles:
    - java
    - common
    - install
    - configure
  post_tasks:
    - include_role:
        name: service
        tasks_from: broker
    - import_role:
        name: serviceState
      vars:
        serviceName: broker
        serviceState: restarted
    - include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ apachePulsarBrokerServicePort }}"
        - "{{ apachePulsarBrokerWebServicePort }}"

- hosts: clusterBookkeeperNodes:clusterBookkeeperAddNodes
  gather_facts: true
  serial: 1
  roles:
    - java
    - common
    - install
    - configure
  post_tasks:
    - include_role:
        name: service
        tasks_from: bookkeeper
    - import_role:
        name: serviceState
      vars:
        serviceName: bookkeeper
        serviceState: restarted
    - include_role:
        name: portCheck
      vars:
        portNumber: "{{ item }}"
        portStatus: started
      loop:
        - "{{ apachePulsarBookiePort }}"
        - "{{ apachePulsarBookieHttpServerPort }}"